# Generated by Django 4.0.5 on 2022-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduceapp', '0002_alter_geust_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geust',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
